function compileSolverInterfaceCode( self )
%COMPILESOLVERINTERFACECODE Compiles the MEX code generated by GENERATESOLVERINTERFACECODE

solverName = self.codeoptions{1}.name;
codeName = [solverName '/interface/' solverName '_optimizerFORCES_interface_mex'];
outputName = ['"' solverName '_optimizerFORCES_interface' '"'];
    


% copy the O-files of all solvers into /interface
% we'll delete them later, but this makes compilation easier
if( ispc )
    copyfile(sprintf('%s/obj/%s.obj',solverName,solverName), sprintf('%s/interface',solverName), 'f');
else % mac or linux
    copyfile(sprintf('%s/obj/%s.o',solverName,solverName), sprintf('%s/interface',solverName), 'f');
end
for i=2:self.numSolvers
    if( ispc )
        copyfile(sprintf('%s_%u/obj/%s_%u.obj',solverName,i,solverName,i), sprintf('%s/interface',solverName), 'f');
    else % mac or linux
        copyfile(sprintf('%s_%u/obj/%s_%u.o',solverName,i,solverName,i), sprintf('%s/interface',solverName), 'f');
    end
end

if exist( [codeName '.c'], 'file' )
    mex('-c','-O','-outdir',[solverName '/interface'],[codeName '.c'])
    if( ispc )
        mex([solverName '/interface/*.obj'], '-output', outputName) 
        delete([solverName '/interface/*.obj']);
    elseif( ismac )
        mex([solverName '/interface/*.o'], '-output', outputName) 
        delete([solverName '/interface/*.o']);
    else % we're on a linux system
        mex([solverName '/interface/*.o'], '-output', outputName,'-lrt') 
        delete([solverName '/interface/*.o']);
    end
else
    fprintf('Could not find source file. This file is meant to be used for building from source code.');
end

end

